service: vibescope-server
frameworkVersion: '3'

plugins:
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  httpApi:
    disableDefaultEndpoint: true
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    PASS: ${self:custom.env.pass}
    YTKEY: ${self:custom.env.ytKey}
  iam: # permissions for functions
    role:
      statements:
        - Effect: Allow
          Action:
            - apigateway:*
            - cloudwatch:*
          Resource: '*'


package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - README.md

functions:
  analyze:
    handler: src/handlers/analyze.analyze
    events:
      - httpApi:
          path: /analyze
          method: post


custom:
  optimize:
    global: true # Minifies node_modules
  stages:
    - dev
    - prod
  env: ${file(env/${self:provider.stage}.yml)}
  customDomain:
    domainName: api.mittaldev.com
    stage: ${self:provider.stage}
    basePath: ${self:custom.env.basePath}
    certificateName: '*.mittaldev.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    autoDomain: false
    apiType: http
